### ISSUE TITLE
Leds data pin connected to low frequency output

### ISSUE THREAD

**Issue by tomy983** [ebastler/zmk-designguide#10]
https://github.com/ebastler/zmk-designguide/blob/feaae1f7793e591d2afa24e0e63899b38bbce676/readme.md?plain=1#L127

In the readme you state that a low frequency pin should not be used for the leds data, but in the pictures and schematic you show the leds data output attached to `P0.09` of the MCU wich is a low frequency pin.

**Comment by ebastler** [comment]
Mh... This must be something I missed when I drew the guide schematic, the labels on the symbol were only added later on.

Thanks for pointing it out, will fix when I have the time.

**Comment by ebastler** [comment]
Sorry it took me so long to address! Moved the pins now.
