### ISSUE TITLE
Does SCL has to connect to a GPIO with AIN functionalitity

### ISSUE THREAD

**Issue by xpol** [ebastler/zmk-designguide#14]
I saw all SCLs in the MCUs are connected to P0.05-A.
So can I choose a GPIO that (is not marked as low freq) does not have an analog input function? E.g. P0.07?

**Comment by ebastler** [comment]
Hi! Whether it has an analog pin alternate function or not does not matter. As long as it is not LF, it is okay for SDA/SCL!
