### ISSUE TITLE
P channel mosfet in underglow example seems to be flipped

### ISSUE THREAD

**Issue by sadekbaroudi** [ebastler/zmk-designguide#8]
https://github.com/ebastler/zmk-designguide#Underglow

![image](https://user-images.githubusercontent.com/299248/209245991-9be944a5-469e-4343-9d34-97bb22819c48.png)

I sent this as a reference on how to to LED firmware enable / disable in ZMK, and someone (Dasky) noticed that it's flipped. Can you confirm?

**Comment by ebastler** [comment]
Damn, you are absolutely right about that - thank you very much for pointing it out, will fix. This is a serious flaw.

**Comment by ebastler** [comment]
Fixed in 1b4583ed1fe225307f807862ee2afc1a4a0c8ec5 - thanks for reporting!

**Comment by sadekbaroudi** [comment]
No problem! Thanks for the quick fix @ebastler
