### ISSUE TITLE
USB ESD Protection Labels wrong?

### ISSUE THREAD

**Issue by OAreiqat** [ebastler/zmk-designguide#9]
The labels on the ESD Protection module seem to be inconsistent with the rest of the schematic. Am I not sure if that's normal or not so I am bringing this up just in case

![image](https://user-images.githubusercontent.com/70589030/210442272-66bd468e-3c39-4fa5-92eb-9a79053192d9.png)

**Comment by ebastler** [comment]
Did not notice, thanks for pointing it out! I will fix it as soon as I find the time. Copied parts of the designguide from projects of mine, and that used a different ESD chip which needs other labels.

**Comment by ebastler** [comment]
I just noticed I only fixed it in the schematic, not yet in the screenshots... Will have to re-take those.
